Repository testshallpass/react-native-dropdownalert, pull requests merged in 2019-06, with the labels that each got.

#197 [Refactor] DropdownAlert internals
  CancelButton.js
  DropdownAlert.js
  Example/App.js
  Example/constants.js
  README.md
  TextView.js
  __tests__/CancelButton-test.js
  __tests__/Constants-test.js
  __tests__/DropdownAlert-test.js
  __tests__/Functions-test.js
  __tests__/TextView-test.js
  __tests__/__snapshots__/CancelButton-test.js.snap
  __tests__/__snapshots__/DropdownAlert-test.js.snap
  __tests__/__snapshots__/TextView-test.js.snap
  constants.js
  docs/PROPS.md
  functions.js
  imageview.js
Labels: task

#199 backgroundColor is read-only
  DropdownAlert.js
Labels: android, hotfix

#203 fix closeInterval set to 0 disable auto close
  DropdownAlert.js
  __tests__/CancelButton-test.js
  __tests__/Constants-test.js
  __tests__/DropdownAlert-test.js
  docs/PROPS.md
Labels: bug, major

#200 onTap prop and payload image source
  DropdownAlert.js
  Example/App.js
  Example/constants.js
  Example/package-lock.json
  Example/package.json
  README.md
  __tests__/CancelButton-test.js
  __tests__/DropdownAlert-test.js
  docs/PROPS.md
Labels: feature request
